version: '3'

services:
  httpd:
    container_name: httpd-container
    build: ./docker/httpd
    ports:
      - "80:80"
  tomcat:
    container_name: tomcat-container
    build: ./docker/tomcat
    volumes:
      - ./target/SpringWebmvcForm.war:/usr/local/tomcat/webapps/SpringWebmvcForm.war
    ports:
      - "8080"
